# https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
# https://symfony.com/doc/4.0/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto
    firewalls:
        main:
            anonymous: true
            stateless: true
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
