monolog:
    handlers:
        filter_for_errors:
            type: fingers_crossed
            action_level: error
            handler: file_log
        file_log:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
            max_files: 3

